
!###################################################
! WARNING:This is a test auto-generated by KROME, in order to
! show a bare-minimal code to call the KROME's subroutine.
! Most of the values could not be appropriate for your
! problem, since this test is only intended as a general
! purpose example.

program test
  use krome_main !use krome (mandatory)
  use krome_user !use utility (for krome_idx_* constants and others)
  implicit none
  integer,parameter::nsp=krome_nmols !number of species (common)
  real*8::Tgas,dt,x(nsp),spy

  spy = 3.65d2 * 2.4d1 * 3.6d3 !seconds per year

  call krome_init() !init krome (mandatory)

  x(:) = 1d-20 !default abundances
  x(krome_idx_H) = 1.d4 !hydrogen initial abundance

  Tgas = 1d3 !gas temperature (K)
  dt = 1d6 * spy !time-step (s)

  !call the solver
  call krome(x(:), Tgas, dt) !call KROME

  print *,"Test OK!"

end program test

